### ISSUE TITLE
`build.util` has no attribute `StrPath`

### ISSUE THREAD

**Issue by sthagen** [jaraco/jaraco.packaging#22]
Just as a heads up (I removed my dependency on pytest-checkdocs to keep my tests succeeding):

```zsh
pytest --asyncio-mode=strict --cov=csaf --cov-report term-missing:skip-covered --cov-branch --log-format="%(levelname)s %(message)s"
Traceback (most recent call last):
  File "/some/venv/python-3.12.1/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/config/__init__.py", line 206, in console_main
    code = main()
           ^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/config/__init__.py", line 159, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/config/__init__.py", line 346, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/helpconfig.py", line 106, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1152, in pytest_cmdline_parse
    self.parse(args)
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1501, in parse
    self._preparse(args, addopts=addopts)
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1388, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/with/python-3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/pytest_checkdocs/__init__.py", line 7, in <module>
    from jaraco.packaging import metadata
  File "/some/venv/with/python-3.12.1/lib/python3.12/site-packages/jaraco/packaging/metadata.py", line 7, in <module>
    source_dir: util.StrPath,
                ^^^^^^^^^^^^
AttributeError: module 'build.util' has no attribute 'StrPath'
make: *** [test] Error 1
```

## Context

- Apple mini M1, 2020
  - 16 GB
- OS Sonoma 14.5
  - Darwin Kernel Version 23.5.0
    - Wed May  1 20:16:51 PDT 2024;
    - root:xnu-10063.121.3~5/RELEASE_ARM64_T8103
    - arm64
- Shell zsh 5.9 (x86_64-apple-darwin23.0)
- Environment manager pyenv 2.3.35-11-g9908daf8
- Base Python 3.12.1
- pytest==8.2.1
- pytest-checkdocs==2.13.0
- build==1.0.3

**Comment by jaraco** [comment]
This issue is reported in the wrong project. The issue is in `jaraco.packaging`. Transferring there.

**Comment by jaraco** [comment]
The issue doesn't occur at head, but does occur with `build==1.0.3`.

**Comment by jaraco** [comment]
That name was introduced in https://github.com/pypa/build/commit/053943e5bb7c36e8f742f68e437219fd492b425c#diff-21b7caef080a777e9e5ee2af03fcf15a84ad67d949fcdafc86d93e37784542fb (build 1.2.0).

**Comment by jaraco** [comment]
That reference was added to jaraco.packaging in 9949286cbd0bba0eba7742d52236ce64945983a9.
